FROM public.ecr.aws/lambda/nodejs:16

RUN yum install -y java-17-amazon-corretto-devel git

USER root
RUN npm install -g --acceptsuitecloudsdklicense @oracle/suitecloud-cli@

COPY . ${LAMBDA_TASK_ROOT}

RUN npm ci && npm run build

CMD [ "dist/app.handler" ]
